### PR TITLE
[CEP-6] Added Vaccination model migration issue frontend and backend changes

### PR DESCRIPTION
**Pull request by hrit2773**
Added all the backend changes and mockups for frontend changes.  @gigincg

### CODE REVIEW

**Comment by vigneshhari** [comment]
I am making some changes to reorganize the files, this would be a decision record, not an enhancement proposal.

**Comment by vigneshhari** [comment]
Can we switch to using a vaccine registry? Enums are hard to manage as they require code changes each time a new vaccine is added. can we switch the design to allow vaccines to be added by admins, very similar to what we have for investigations.

**Comment by vigneshhari** [comment]
Assigned CEP 6 for this enhancement.

**Comment by hrit2773** [comment]
> Can we switch to using a vaccine registry? Enums are hard to manage as they require code changes each time a new vaccine is added. can we switch the design to allow vaccines to be added by admins, very similar to what we have for investigations.
@vigneshhari yes we can do that cc: @gigincg

**Comment by gigincg** [comment]
@vigneshhari This will be covered the Health Details APIs right?

**Comment by bodhish** [comment]
This should be rebuild following the HL7 FHIR standard

**Comment by vigneshhari** [comment]
Closing because of no activity

**Pull request closed without merging**
