### PR TITLE
Add docs for discharge summary

### PR DESCRIPTION
**Pull request by Ashesh3**
Add initial technical docs for https://github.com/coronasafe/discharge_summary

### CODE REVIEW

**Comment by bodhish** [comment]
@Ashesh3 can we get this merged

**Comment by bodhish** [comment]
@Ashesh3 poke, @nihal467 do we have this feature live?

**Comment by nihal467** [comment]
@bodhish The feature is not live on the platforms yet; only a demo was completed during an EOD call few months back.

**Comment by Ashesh3** [comment]
> @Ashesh3 can we get this merged

Hey, this is ready to be merged from my side. Let me know if any changes are required. I am waiting on a review and merge.

**Pull request closed without merging**
