### PR TITLE
[CEP-11] Proposal for adding tags feature

### PR DESCRIPTION
**Pull request by therurouni**
I made the proposal for issue  https://github.com/ohcnetwork/care_fe/issues/8646

### CODE REVIEW

**Comment by bodhish** [comment]
@PAVAN507-STAR please do have a dicussion with @gigincg @vigneshhari in [Slack](https://slack.ohc.network/). #care_product channel.

**Comment by therurouni** [comment]
> @PAVAN507-STAR please do have a dicussion with @gigincg @vigneshhari in [Slack](https://slack.ohc.network/). #care_product channel.

Yeah okay

**Comment by vigneshhari** [comment]
There is a lot of rework required, i have shared the requirements over slack DM, it might be better to close this and recreate when needed.

**Comment by bodhish** [comment]
@PAVAN507-STAR can you update the status here?

**Comment by therurouni** [comment]
@bodhish @vigneshhari  sir  i'll be honest ,I'm sorry the proposal i gave is not mine.I'm 2nd yr ug i don't know much about how to make a proposal nor got much idea about how to solve this issue in particular .But now i've realized my mistake and so i can guarantee you that i will  work on this issue  and solve it with some guidance and help from both of you sir(if u don't mind)

**Comment by vigneshhari** [comment]
Closing this MR, please make a draft MR when you complete the doc

**Comment by PAVAN507-STAR** [comment]
> Closing this MR, please make a draft MR when you complete the doc

sir can u guide me a bit on how to make a proposal if u don't mind

**Pull request closed without merging**
